name: weather_app
description: Weather application
publish_to: 'none'
version: 1.0.0+10000

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ui
  cupertino_icons: ^1.0.2

  # state manager, di, navigation, localization
  get: ^4.6.1

  # local storage
  hive: ^2.0.5
  hive_flutter: ^1.1.0

  # http
  dio: ^4.0.4
  pretty_dio_logger: ^1.1.1

  # location
  geolocator: ^8.0.1
  geocoding: ^2.0.1

  # utils
  permission_handler: ^8.3.0
  package_info_plus: ^1.3.0
  url_launcher: ^6.0.17
  connectivity_plus: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  ios: true
  android: true
  image_path: 'assets/png/app_icon.png'

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/png/
